language: java

jdk:
  - oraclejdk8

before_install:
#  - mvn install -Dmaven.javadoc.skip=true
   - "echo skipped"
install:
  - "echo skipped"
script:
#  - "echo skipped" 
  - mvn install -Dmaven.javadoc.skip=true
# - mvn deploy
notifications:
  email:
    recipients:s
      - 1569376982@qq.com
    #on_success: [always|never|change]  default: change
    #on_failure: [always|never|change]  default: always